### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JackPlaysGames0510** [BillyCurtis/OpenDiscordSafariExtension#1]
https://github.com/BillyCurtis/OpenDiscordSafariExtension/assets/48178959/2667538f-6a16-42c2-98b0-64ed7325e0bf
is it possible to fix?

**Comment by JackPlaysGames0510** [comment]
Ok I found out that the app has to be closed to use it is their a way to fix that so you can use while the app is open

**Comment by JackPlaysGames0510** [comment]
Never mind It still doesn’t work sometimes when the app closes

**Comment by BillyCurtis** [comment]
can you give me the link that your trying to use? As it looks like it's checking to see if Discord from the App Store is installed and if not it's redirecting you to download it so that's why it's not working 

As the Open in Discord popup only currently works for discord.com/invite/* or discord.com/channels/* links

**Comment by JackPlaysGames0510** [comment]
I use this and I do have some problems
https://discord.com/invite/enmityapp

**Comment by BillyCurtis** [comment]
Are you sure you have the Extension enabled and set to Allow? as using that link works with both Discord closed and open

https://github.com/BillyCurtis/OpenDiscordSafariExtension/assets/38408756/9db92c17-d81d-49dd-ac42-30e24f795211

**Comment by JackPlaysGames0510** [comment]
Yes it’s doing the wired thing when it works when the app is closed but when it opens it doesn’t work

**Comment by JackPlaysGames0510** [comment]
https://github.com/BillyCurtis/OpenDiscordSafariExtension/assets/48178959/051f8e4a-c311-4f39-982c-27417bf03982

**Comment by BillyCurtis** [comment]
Does this happen with other invite links? As I think this might be an issue with the Enmity tweak since discord.com/invite/* links work fine on the stock app but when Enmity is injected some links don't popup in app and only work when the app is closed from my testing it was only https://discord.com/invite/enmityapp that didn't work when the app was open but https://discord.com/invite/jb did

**Comment by JackPlaysGames0510** [comment]
Yeah your right is their a way to fix that

**Comment by BillyCurtis** [comment]
the only thing i found that works for the Enmity link is changing one the letters to an uppercase https://discord.com/invite/Enmityapp works

**Comment by JackPlaysGames0510** [comment]
Yeah it did work

**Comment by BillyCurtis** [comment]
i added a hardcoded link for the Enmity vanity url can you try now?

**Comment by JackPlaysGames0510** [comment]
ok thanks

**Comment by JackPlaysGames0510** [comment]
Works a lot better now
